#include "UnitTestAttacher.h"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void StartUnitTest() 
{
	configMotor(Motor, port1, "motor1", tmotorVex393_HBridge, openLoop);
	configMotor(Motor, port2, "motor2", tmotorVex393_MC29, openLoop);
	configMotor(Motor, port3, "motorNormal", tmotorVex393_MC29, openLoop);
}

task smh()
{



}